---
version: 2.1
orbs:
  slack: circleci/slack@4.4.4
jobs:
  lint:
    docker:
      - image: fedora:32
    steps:
      - run: dnf install -y make
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install-deps
            pip install --require-hashes -r requirements/dev-requirements.txt
      - run:
          name: Run linters
          command: make lint
      - slack/notify:
          channel: C01EY9C1X45
          event: fail
          template: basic_fail_1
  build-rpm:
    docker:
      - image: fedora:32
    steps:
      - run: dnf install -y make
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install-deps
            pip3 install --require-hashes -r requirements/dev-requirements.txt
      - run:
          name: Build RPM
          command: make build-rpm
      - run:
          name: Check reproducibility
          command: make reprotest
      - slack/notify:
          channel: C01EY9C1X45
          event: fail
          template: basic_fail_1
  test:
    docker:
      - image: fedora:32
    steps:
      - run: dnf install -y make
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install-deps
            pip3 install --require-hashes -r requirements/dev-requirements.txt
      - run:
          name: Run tests
          command: make test
      - slack/notify:
          channel: C01EY9C1X45
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  securedrop_updater_ci:
    jobs:
      - lint
      - build-rpm
      - test
      - lint:
          context:
            - circleci-slack
      - build-rpm:
          context:
            - circleci-slack
      - test:
          context:
            - circleci-slack
