---
version: 2
jobs:
  lint:
    docker:
      - image: fedora:32
    steps:
      - run: dnf install -y make
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install-deps
            pip install --require-hashes -r requirements/dev-requirements.txt
      - run:
          name: Run linters
          command: make lint
  build-rpm:
    docker:
      - image: fedora:32
    steps:
      - run: dnf install -y make
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install-deps
            pip3 install --require-hashes -r requirements/dev-requirements.txt
      - run:
          name: Build RPM
          command: make build-rpm
      - run:
          name: Check reproducibility
          command: make reprotest
  test:
    docker:
      - image: fedora:32
    steps:
      - run: dnf install -y make
      - checkout
      - run:
          name: Install dependencies and run tests
          command: |
            make install-deps
            pip3 install --require-hashes -r requirements/dev-requirements.txt
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  securedrop_updater_ci:
    jobs:
      - lint
      - build-rpm
      - test
